version: "3"
services:
  tasks-md:
      hostname: tasks-md
      container_name: tasks-md
      image: baldissaramatheus/tasks.md
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
          - api-data:/api/files
          - stylesheets-data:/api/static/stylesheets/
      restart: unless-stopped
      ports:
        - 8080:8080
volumes:
  api-data:
    driver: local
  stylesheets-data:
    driver: local
